import { createClient } from "@supabase/supabase-js";

type ReviewRow = { id: string; name: string; rating: number; message: string; created_at: string };
const fields = "id,name,rating,message,created_at";
function database() { const url = process.env.SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; return url && key ? createClient(url, key) : null; }
function mapReview(review: ReviewRow) { return { id: review.id, name: review.name, rating: review.rating, message: review.message, createdAt: review.created_at }; }

export async function GET() { const db = database(); if (!db) return Response.json({ reviews: [] }); const { data, error } = await db.from("reviews").select(fields).eq("is_visible", true).order("created_at", { ascending: false }); if (error) return Response.json({ reviews: [] }); return Response.json({ reviews: (data as ReviewRow[]).map(mapReview) }); }
export async function POST(request: Request) { const db = database(); if (!db) return Response.json({ error: "Reviews are not configured yet." }, { status: 503 }); try { const body = await request.json(); const rating = Number(body.rating); const name = typeof body.name === "string" ? body.name.trim() : ""; const email = typeof body.email === "string" ? body.email.trim() : ""; const message = typeof body.message === "string" ? body.message.trim() : ""; if (!Number.isInteger(rating) || rating < 1 || rating > 5 || message.length < 10 || message.length > 2000 || name.length > 80 || email.length > 254) return Response.json({ error: "Please provide a valid rating and review." }, { status: 400 }); const { data, error } = await db.from("reviews").insert({ name: name || "Anonymous customer", email: email || null, rating, message, is_visible: true }).select(fields).single(); if (error || !data) throw error; return Response.json({ review: mapReview(data as ReviewRow) }); } catch { return Response.json({ error: "Unable to publish review." }, { status: 500 }); } }
